### ISSUE TITLE
hyper::Error(IncompleteMessage) at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by log2cn** [Millione/nju-clock-in#11]
[2022-05-10T10:19:31Z INFO  nju_clock_in] try to clock in, times: 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("ehallapp.nju.edu.cn")), port: None, path: "/xgfw/sys/yqfxmrjkdkappnju/apply/getApplyInfoList.do", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) }', src/main.rs:69:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Millione** [comment]
最新版本已修复！
