### ISSUE TITLE
最近一次核酸检测显示问题

### ISSUE THREAD

**Issue by Miraitowa2001** [Millione/nju-clock-in#4]
若通过app手动打卡，其显示格式为：2022-04-12 11 
若通过该途径打卡，其显示格式为：2022-04-12-11

区别在于日期与小时数之间为空格或横杠，不知道是否会影响后台数据导出统计。

**Comment by Millione** [comment]
感谢反馈，据我实测是不会有影响的（因为我不在缺少检测时间的被通报名单中23333）

不过格式问题确实是bug，目前已修复， 为稳妥起见，可更新至最新版本。
