### ISSUE TITLE
action运行报错

### ISSUE THREAD

**Issue by log2cn** [Millione/nju-clock-in#8]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("ehallapp.nju.edu.cn")), port: None, path: "/xgfw/sys/yqfxmrjkdkappnju/apply/saveApplyInfos.do", query: Some("WID=DD05635A0D804339E0533473DBDB9AE5&IS_TWZC=1&CURR_LOCATION=***&ZJHSJCSJ=[20](https://github.com/191840239/nju-clock-in/runs/6094505758?check_suite_focus=true#step:6:20)22-04-17%2010&JRSKMYS=1&IS_HAS_JKQK=1&JZRJRSKMYS=1&SFZJLN=0"), fragment: None }, source: hyper::Error(IncompleteMessage) }', src/main.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Process completed with exit code 101.

**Comment by Millione** [comment]
应该只是网络问题，可以重新跑一下workflow。当然，也可以修改cron定时规则，在不同时间段进行打卡，多次打卡不会有实际影响。

**Comment by log2cn** [comment]
感谢！

**Comment by log2cn** [comment]
您好 我在今天不同时间3次执行action 皆报此错 （我也尝试了重新fork 但是没有解决）

**Comment by Millione** [comment]
目前原因还没法下定论，刚更新了随机化User-Agent请求头，防止限制访问速率或拉入黑名单，但从结果来看和之前没什么差别，时好时不好

**Comment by log2cn** [comment]
貌似学校那边的接口变了？

**Comment by Millione** [comment]
抓包看了下，新增了Referer请求头，应该是能使了

**Comment by log2cn** [comment]
过了 谢谢！
