### ISSUE TITLE
随机地报错 “login in failed”

### ISSUE THREAD

**Issue by log2cn** [Millione/nju-clock-in#9]
随机地报如下错误
thread 'main' panicked at 'login in failed, maybe caused by password error or captcha missed, please check and try again', src/main.rs:59:9

**Comment by Millione** [comment]
应该是验证码识别出错，目前采用的ocr识别成功率不高，项目里是尝试10次，可以增大尝试次数或者重跑一次

**Comment by log2cn** [comment]
原来如此！感谢！
